emdb/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from registeration.views import  AboutView
app_name='emdb'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls',namespace='movies')),
    path('login/', include('registeration.urls',namespace='registeration')),
    path('review/', include('review.urls',namespace='review')),
    path('', include('movies.urls',namespace='movies')),
    path('about/', AboutView.as_view(), name ='about'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path,include
from movies.views import HomeView, BrowseView, MovieView
from . import views

app_name = 'movies'
urlpatterns = [
	path('', HomeView.as_view(), name='home'),
	path('home', HomeView.as_view()),
	path('browse', BrowseView.as_view(), name='browse'),
	path('movie/<int:pk>', MovieView.as_view(), name='movie'),
]

registeration/urls.py
from django.urls import path
from registeration.views import LoginView, RegisterView, LogoutView ,ProfileView
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'registeration'
urlpatterns = [
	path('', LoginView.as_view(), name = 'login'),
	path('register', RegisterView.as_view(), name = 'register'),
	path('logout',LogoutView.as_view(),name ='logout'),
    path('profile',  ProfileView.as_view(), name = 'profile'),
]

movies/models.py
from django.db import models

class Movie (models.Model):
	name = models.CharField(max_length=250)
	production_date = models.DateField()
	description = models.CharField(max_length=10000)
	rate = models.FloatField()
	trailer_url = models.CharField(max_length=1000)
	movie_logo = models.CharField(default='',max_length=1000)
	genre = models.CharField(default='', max_length=250)


	def __str__(self):
		return self.name+' - '+ str(self.production_date)

class Actor(models.Model):
    name = models.CharField(max_length=250)
    movies = models.ManyToManyField(Movie)
    photo = models.CharField(default='',max_length=1000)

    def __str__(self):
        return self.name

class Director(models.Model):
    name = models.CharField(max_length=250)
    movies = models.ManyToManyField(Movie)
    photo = models.CharField(default='',max_length=1000)

    def __str__(self):
        return self.name

class Writer(models.Model):
    name = models.CharField(max_length=250)
    movies = models.ManyToManyField(Movie)
    photo = models.CharField(default='',max_length=1000)

    def __str__(self):
        return self.name

movies/forms.py
from django import forms

class BrowseForm (forms.Form):
    search= forms.CharField(required=False , widget=forms.TextInput(attrs={'class': 'form-control',}))

    GenresType = (('', 'All'), ('Action', 'Action'),('Adventure','Adventure'), ('Comedy', 'Comedy'), ('Crime', 'Crime'),
                  ('Drama', 'Drama'), ('Horro', 'Horro'),('History','History'))
    genre=forms.ChoiceField(choices=GenresType,label='',initial='', widget=forms.Select(attrs={'class': 'spinner',}), required=False)

    SortBy = (("production_date", 'Production Date'), ("name", 'Name'))
    sort = forms.ChoiceField(choices=SortBy,label='',initial='', widget=forms.Select(attrs={'class': 'spinner', }), required=False)

movies/views.py
from django.core.paginator import Paginator
from django.views.generic import TemplateView, ListView
from movies.forms import BrowseForm
from movies.models import Movie, Director, Writer,Actor
from django.shortcuts import render, redirect
from review.models import Review
from registeration.models import User
from django.db import connection

class HomeView(TemplateView):
    template_name = "movies/home.html"

    def get(self, request):
        #latest_movies = list(Movie.objects.order_by("-production_date").values_list('movie_logo', flat=True)[:5])
        with connection.cursor() as cursor:
            cursor.execute("SELECT movie_logo  FROM movies_movie  order by -production_date ")
            latest_movies = [i[0] for i in list(cursor.fetchall())[:5]]
        print(latest_movies)
        movies_id = list(Movie.objects.order_by("-production_date").values_list('id', flat=True)[:5])
        return render(request, self.template_name, {'latest_movies': latest_movies, 'movies_id':movies_id})


class MovieView(ListView):
    template_name = "movies/moviepage.html"

    def get(self, request, *args, **kwargs):
        #movie = Movie.objects.get(id=kwargs['pk'])
        movie = Movie.objects.raw("SELECT * FROM movies_movie where id =%s",[kwargs['pk']])[0]
        #directors = movie.director_set.all()
        directors = Director.objects.raw("SELECT * FROM movies_director, movies_director_movies\
        WHERE movies_director.id = movies_director_movies.director_id AND movie_id = %s",
                                         [kwargs['pk']])
        #writers = movie.writer_set.all()
        writers = Writer.objects.raw("SELECT * FROM movies_writer, movies_writer_movies\
                WHERE movies_writer.id = movies_writer_movies.writer_id AND movie_id = %s",
                                         [kwargs['pk']])

        #actors = movie.actor_set.all()
        actors = Actor.objects.raw("SELECT * FROM movies_actor, movies_actor_movies\
                WHERE movies_actor.id = movies_actor_movies.actor_id AND movie_id = %s",
                                         [kwargs['pk']])

        #reviews = Review.objects.filter(movie=movie)
        reviews = Review.objects.raw("SELECT * FROM review_review where movie_id = %s", [kwargs['pk']])
        arg = {'movie': movie, 'directors': directors, 'writers': writers, 'actors': actors, 'reviews': reviews}
        if request.user.is_authenticated:
            #user = User.objects.get(id=request.user.id)
            user = User.objects.raw("SELECT * FROM registeration_user WHERE id = %s",[request.user.id])[0]
            #r = Review.objects.filter(movie=movie, created_by=user)
            r = Review.objects.raw("SELECT * FROM review_review where movie_id = %s AND created_by_id = %s",
                                   [movie.id,user.id])
            arg['review'] = r
            print(arg)
        return render(request, self.template_name, arg)


class BrowseView(ListView):
    template_name = "movies/browse.html"

    def get(self, request):
        search = request.GET.get('search')
        if(not search):
            search = ""

        genre = request.GET.get('genre')
        if (not genre):
            genre = ""
        sort = request.GET.get('sort')
        if (not sort):
            sort = "-production_date"

        form = BrowseForm(initial={'sort':sort,'search':search,'genre':genre})
        #all_movies = Movie.objects.filter(name__contains=search,
         #                                 genre__contains=genre).order_by(sort)
        all_movies = list(Movie.objects.raw("select * from movies_movie\
         where name like '%%" +search+ "%%' AND genre like '%%"+genre+"%%' ORDER by %s ASC",[sort]))
        paginator = Paginator(all_movies, 9)  # Show 9 contacts per page
        page = request.GET.get('page')
        if page == None:
            page = 1
        movies = paginator.get_page(page)
        arg = {'movies': movies, 'form': form}
        return render(request, self.template_name, arg)

movies/templates/movies/browse.html
<!DOCTYPE html>
<html>
    <head>
        <title>Browse</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'emdb/css/pagestyle.css'%}">
        <link rel="stylesheet" type="text/css" href="{% static 'movies/css/browsestyle.css'%}">
        <link href='https://fonts.googleapis.com/css?family=Courgette' rel='stylesheet'>
        <link href='https://fonts.googleapis.com/css?family=Didact Gothic' rel='stylesheet'>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    </head>    
    <body >

        <ul>
            <li><a href="home">Home</a></li>
            <li><a class="active" href="browse">Browse</a></li>
            <li><a href="/about">About</a></li>
            {% if user.is_authenticated %}
                <li style="float:right" ><a href="{% url 'registeration:logout' %}">Logout</a></li>
                <li style="float:right"><a href="{% url 'registeration:profile' %}">{{ user.first_name }}</a></li>
            {% else %}
                <li style="float:right"><a href="{% url 'registeration:login' %}">Login</a></li>
            {% endif %}
        </ul>
        
        <h1 class="head-textbox" style="text-align: center;">
            Browse Movies
        </h1>

        <form class="search" action="{% url 'movies:browse' %}" method="get">
            <div class="textbody-left">
                <p style="margin-bottom: -2%;">Genre:</p>
                    {{ form.genre }}
            </div>
            <div class="textbody-right">    
                <p style="margin-bottom: -2%;">Sort by:</p>
                    {{ form.sort }}
            </div>

            <div style= "margin-left: 30%; max-width:600px;">
                    {{ form.search }}
            </div>
            <button style="margin-top: 1.3%; width: 10%; " type="submit"><i class="fa fa-search"></i></button>
        </form>

        <!-- !PAGE CONTENT! -->
        <!-- First Photo Grid-->
        <div class="browse-pages" style="width: 100%; padding: 30px;">
                <a><<img src="" class="cover-photo" style="margin-left: 16%"></a>
                <a><img src="" class="cover-photo"></a>
                <a><img src="" class="cover-photo"></a>
        </div>
        
        <!-- Second Photo Grid-->
        <div class="browse-pages" style="width: 100%; padding: 30px;">
                <a><<img src="" class="cover-photo" style="margin-left: 16%"></a>
                <a><img src="" class="cover-photo"></a>
                <a><img src="" class="cover-photo"></a>
        </div>

        <!-- Third Photo Grid -->
        <div class="browse-pages" style="width: 100%; padding: 30px;">
                <a><<img src="" class="cover-photo" style="margin-left: 16%"></a>
                <a><img src="" class="cover-photo"></a>
                <a><img src="" class="cover-photo"></a>
        </div>
        {% load movies_extras %}
        <!-- Pagination -->
        {% if movies %}
            <div class="pagination" style="text-align: center;">
                {% if movies.has_previous %}
                    <a href="?{% url_replace request 'page' movies.previous_page_number %}">&laquo;</a>
                {% endif %}
                {% for pg in movies.paginator.page_range %}
                    {% if movies.number == pg %}
                        <a class="active" href="?{% url_replace request 'page' pg %}">{{ pg }}</a>
                    {% else %}
                        <a href="?{% url_replace request 'page' pg %}">{{ pg }}</a>
                    {% endif %}
                {% endfor %}
                {% if movies.has_next %}
                    <a href="?{% url_replace request 'page' movies.next_page_number %}">&raquo;</a>
                {% endif %}
            </div>
        {% endif %}


        <script>
            var SLIDES_COUNT = 9;
            var slidesSrc = [];
            var slidesRef = []
            {% for movie in movies %}
                slidesSrc.push("{{ movie.movie_logo }}");
                slidesRef.push("{{movie.id}}");
            {% endfor %}
            showSlides();

            function showSlides() {
                var i;
                var slides = document.getElementsByClassName("cover-photo");

                for(i = 0; i < SLIDES_COUNT ; i ++) {
                    if (i < slidesSrc.length) {
                        slides[i].src = slidesSrc[i];
                        slides[i].parentNode.href = "movie/" + slidesRef[i];
                    }
                    else {
                        slides[i].src = "";
                         slides[i].href = "";
                    }
                }
            }


        </script>

    </body>
</html>

movies/templates/movies/create.html
<!DOCTYPE html>
<html>
 <head>
    <meta charset="utf-8/">
    <title>hello login</title>
    <link rel="stylesheet" type="text/css" href="css/create.css"> 
    <link rel="stylesheet" type="text/css" href="css/pagestyle.css">   
    <link href='https://fonts.googleapis.com/css?family=Courgette' 
		rel='stylesheet'>
		<link href='https://fonts.googleapis.com/css?family=Didact Gothic' 
		rel='stylesheet'>
 </head>
 <body>
		<ul>
		  <li><a  
		  	href="home.html">Home</a></li>
		  <li><a href="history.html">Browse</a></li>
		  <li><a href="contact.html">Contact Us</a></li>
		  <li style="float:right"><a class="active" 	href="login.html">Login</a></li>
		</ul>
  
    <div class="create">
      <form name="register">							
				<label >First name</label>
        <input type="text" name="firstname" placeholder="first name"><br>
        <label >Last name</label>
        <input type="text" name="lname" placeholder="last name"><br>
        <label >Your email</label>
        <input  type="email" name="email" placeholder="examble@host.com"><br>
        <label >Create  Password</label>
        <input  type="password" name="Your Password" placeholder="Your Password"><br>				
				<label>Confirm  Password</label>
        <input type="password" name="Your Password" placeholder="confirm  Password"><br>
        <input type="submit" value="Create">
        <input type="reset" value="Reset">
      </form>
    </div>
  
 </body>
</html>

movies/templates/movies/home.html
<!DOCTYPE html>
<html>
	<head>

		<title>EMDB</title>
		{% load static %}
		<link rel="stylesheet" type="text/css" href="{% static 'emdb/css/pagestyle.css'%}">  
		<link href='https://fonts.googleapis.com/css?family=Courgette' 
		rel='stylesheet'>
		<link href='https://fonts.googleapis.com/css?family=Didact Gothic' 
		rel='stylesheet'>

		<style type="text/css">
			/* Next & previous buttons */
			.prev, .next {
				cursor: pointer;
				position: absolute;
				top: 50%;
				width: auto;
				padding: 16px;
				margin-top: 4%;
				color: white;
				font-weight: bold;
				font-size: 18px;
				transition: 0.6s ease;
				border-radius: 0 3px 3px 0;
			}

			/* Position the "next button" to the right */
			.next {
			  right: 0;
			  border-radius: 3px 0 0 3px;
			}
			.prev{
				left:0;
			}

			/* On hover, add a black background color with a little bit see-through */
			.prev:hover, .next:hover {
				background-color: rgba(0,0,0,0.8);
				font-size: 25px;
			}
		</style>

	</head>


	<body>

		<ul>
		  <li><a class="active" 
		  	href="home">Home</a></li>
		  <li><a href="browse">Browse</a></li>
		  <li><a href="/about">About</a></li>
          {% if user.is_authenticated %}
                <li style="float:right" ><a href="{% url 'registeration:logout' %}">Logout</a></li>
                <li style="float:right" ><a href="{% url 'registeration:profile' %}">{{ user.first_name }}</a></li>
            {% else %}
                <li style="float:right"><a href="{% url 'registeration:login' %}">Login</a></li>
            {% endif %}
		</ul>

		<h1 class="head-textbox" style="text-align: center;">
			Egyptian Movies Database
		</h1>

		<h2 class="sub-textbox" style="text-align: center;">
			The Latest Movies
		</h2>
		<div style="width: 100%;">

			  <a href=""><img src="" class="cover-photo" style="margin-left: 16%"></a>
	      
			<a href=""><img src="" class="cover-photo"></a>

			  <a href="" ><img src="" class="cover-photo"></a>

        
	      <script src ="{% static 'movies/scripts/slideshow.js' %}">
        </script>
        <script>
         setSlides({{latest_movies|safe}},{{movies_id|safe}});
        </script>
		<a class="prev" onclick="plusSlides(-1)">&#10094;</a>
		<a class="next" onclick="plusSlides(1)">&#10095;</a>
    

	</body>
</html>

movies/templates/movies/moviepage.html
<!DOCTYPE html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <title> Movie Details</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'emdb/css/pagestyle.css'%}">  
    <link rel="stylesheet" type="text/css" href="{% static 'movies/css/moviestyle.css'%}">
      <link href='https://fonts.googleapis.com/css?family=Courgette' rel='stylesheet'>
      <link href='https://fonts.googleapis.com/css?family=Didact Gothic' rel='stylesheet'>

  </head>
  <body>

    <ul>
		  <li><a href="{% url 'movies:home' %}">Home</a></li>
          <li><a href="{% url 'movies:browse' %}">Browse</a></li>
		  <li><a href="/about">About</a></li>
		  {% if user.is_authenticated %}
                <li style="float:right" ><a href="{% url 'registeration:logout' %}">Logout</a></li>
                <li style="float:right" ><a href="{% url 'registeration:profile' %}">{{ user.first_name }}</a></li>
            {% else %}
                <li style="float:right"><a href="{% url 'registeration:login' %}">Login</a></li>
            {% endif %}
    </ul>


    <div class="grid-container">
      <div class="item1">
        <h1 class="sub-textbox">{{movie.name}}</h1>
        <h2>★</h2>
        <h4 class="sub-textbox">{{ movie.rate }}/10</h4>
        <img class="Movie-photo" src="{{ movie.movie_logo }}" />
      </div>
      <div class="item2"><iframe class="video" src="{{ movie.trailer_url }}"></iframe></div>
    </div>
    <hr><br>
    <div class="details">
      <h4 class="sub-textbox" style="text-decoration: underline;">Storyline :</h4>
      <p class="body-textbox">{{ movie.description }}</p>
      <hr><br>

      <h4 class="sub-textbox"style="text-decoration: underline;">Director :</h4>
        {% for director in directors %}
      <div class="cast">
        <div class="chip">
          <img src="{{ director.photo }}" alt="Person" width="96" height="96">
          {{ director.name }}
        </div><br><br>
      </div>
        {% endfor %}
      <h4 class="sub-textbox"style="text-decoration: underline;">Writer :</h4>
        {% for writer in writers %}
      <div class="cast">
        <div class="chip">
          <img src="{{ writer.photo }}" alt="Person" width="96" height="96">
          {{ writer.name }}
        </div><br><br>
      </div>
        {% endfor %}

      <hr><br>
      <h4 class="sub-textbox" style="text-decoration: underline;">Cast :</h4>
      <div class="cast">
          {% for actor in actors %}
        <div class="chip">
          <img src="{{ actor.photo }}" alt="Person" width="96" height="96">
          {{ actor.name }}
        </div><br><br>
          {% endfor %}

      </div>
    </div><hr>

    <div class="commintsList">
      <h4 class="sub-textbox" style="text-decoration: underline;">Comments :</h4>
      {% for r in reviews %}
      <div style="padding:4%;">
        <div>
        <h4 class="body-textbox"style="text-decoration: underline;float:left">{{r.created_by.first_name}} {{r.created_by.last_name}}</h4>
        <p class="body-textbox" style="margin-left:50%;float:left; margin-right: 5%">★{{r.rate}}/5</p>
        </div>
        <div>
        <p class="body-textbox">{{r.comment}}</p>
        </div>
      </div><hr><br>
      {% endfor %}
    </div>


    <form class="review" action="/review/{{movie.pk}}/add_review/" method="post"><br>
      {% csrf_token %}
      <div class="comment">
        <h4 class="body-textbox">Comment :</h4>
        <textarea rows="7" name="comment" type="text">{{review.comment}}</textarea>
      </div><br>
      <div class="rating">
        <legend class="body-textbox">Rate:</legend>
        <input type="radio" name="rate" type="number" id="star5"  value="5" checked /><label for="star5"></label>
        <input type="radio" name="rate" type="number" id="star4"  value="4" /><label for="star4"></label>
        <input type="radio" name="rate" type="number" id="star3"  value="3" /><label for="star3"></label>
        <input type="radio" name="rate" type="number" id="star2"  value="2" /><label for="star2"></label>
        <input type="radio" name="rate" type="number" id="star1"  value="1" /><label for="star1"></label>
			</div>
      <button type="submit" class="button">Submit</button>
    </form>
    

  </body>

  </html>